--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.cities(CityID, City, CountyOrRegionID) VALUES
(1, 'Birmingham', 1),
(2, 'Liverpool', 2),
(7, 'Stoke on Trent', 5),
(8, 'London', 6),
(10, 'Birmingham', 7);