--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.credits(CreditID, CustomerID, TransactionDate, Credit) VALUES
(1, 1, '2012-02-01 00:00:00', 5.00000000000),
(2, 1, '2012-02-02 00:00:00', 10.00000000000),
(3, 1, '2012-02-03 00:00:00', 4.00000000000),
(4, 2, '2012-03-03 00:00:00', 7.00000000000),
(5, 2, '2012-03-05 00:00:00', 5.00000000000),
(6, 3, '2012-03-10 00:00:00', 20.00000000000);