--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.debits(DebitID, CustomerID, TransactionDate, Debit) VALUES
(1, 1, '2012-02-03 00:00:00', 8.00000000000),
(2, 1, '2012-02-04 00:00:00', 2.00000000000),
(3, 2, '2012-03-04 00:00:00', 8.00000000000);