--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.employeecourselog(CourseDate, EmployeeID, CourseID, QualificationID, Passed) VALUES
('2017-10-09 00:00:00', 1, 1, 1, 1),
('2018-07-16 00:00:00', 2, 3, 2, 1),
('2018-07-23 00:00:00', 1, 2, 3, 1);