--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.orders(OrderID, CustomerID, EmployeeID, OrderDate, PurchaseOrderNumber, ShipDate, ShippingMethodID, FreightCharge, Taxes, PaymentReceived, Comment) VALUES
(1, 2, 1, '2005-04-23 00:00:00', '10', '2005-04-29 00:00:00', 1, 64.00000000000, 5, 0, NULL),
(2, 1, 1, '2005-03-23 00:00:00', '11', '2005-03-29 00:00:00', 1, NULL, 5, 0, NULL),
(3, 3, 3, '2005-01-21 00:00:00', '30', '2005-06-28 00:00:00', 5, NULL, 5, 0, NULL),
(4, 2, 2, '2005-05-05 00:00:00', '26', '2005-09-19 00:00:00', 2, NULL, 5, 0, NULL),
(5, 4, 5, '2005-05-02 00:00:00', '32', '2005-09-27 00:00:00', 2, NULL, 5, 0, NULL),
(13, 1, 1, '2008-02-29 00:00:00', '1', NULL, 2, 50.00000000000, 5, 0, NULL);