--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.qryorderdetails(OrderNumber, ProductID, Quantity, UnitPrice, NetAmount) VALUES
('20111208103010', 1, 30, 2.50000000000, 75.00000000000),
('20111209141055', 3, 40, 7.50000000000, 300.00000000000),
('20111209141055', 2, 10, 5.00000000000, 50.00000000000),
('20111208103010', 2, 20, 4.25000000000, 85.00000000000),
('20111208103010', 5, 1, 12.75000000000, 12.75000000000);