--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.qualifications(QualificationID, Qualification) VALUES
(0, 'N/A'),
(1, 'Certificate in basic widget handling'),
(2, 'Certificate in advanced widget design'),
(3, 'Certificate in widget fabrication');