--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.stockacquisitions(AcquisitionDate, ProductID, Quantity) VALUES
('2011-04-01 00:00:00', 5, 10),
('2011-06-01 00:00:00', 1, 100),
('2011-08-01 00:00:00', 1, 150),
('2011-08-01 00:00:00', 3, 50),
('2011-09-01 00:00:00', 2, 120);