--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.tbldrawingmaster(DrawingID, ProjectName, Status, ApprovedRevision, ApprovedDate) VALUES
(1, 'XYZ Company Project 1', 'Unapproved', NULL, NULL),
(2, 'ABC Company Project 3', 'Approved', '2', '2015-03-30 00:00:00'),
(3, 'PDQ Company Project 6', 'Unapproved', NULL, NULL);