--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.tbllocation(RevisionID, DrawingID, Revision, Location, Comment) VALUES
(1, 1, '0', 'SubContractor', 'Need stormwater spec'),
(2, 1, '1', 'Home', 'Received 3/24 - sent to Bob at XYZ'),
(3, 1, '1', 'Client', NULL),
(4, 2, '0', 'SubContractor', 'Need input on atrium'),
(5, 2, '0', 'Client', 'Had sub courier to ABC'),
(6, 2, '0', 'Home', 'Rec''d with atrium input'),
(7, 2, '0', 'SubContractor', NULL),
(8, 2, '1', 'Home', 'Modified with revised atrium'),
(9, 2, '1', 'Client', 'Replace fountain with water wall'),
(10, 2, '1', 'Home', NULL),
(11, 3, '0', 'SubContractor', 'Project specs sent 2/16'),
(12, 3, '0', 'Home', 'Drawing received 3/2, sent to PDQ 3/3'),
(13, 3, '0', 'Client', 'Returned 3/4 with updated spec'),
(14, 3, '0', 'Home', 'Reviewed specs conf call with subcontractor'),
(15, 3, '0', 'SubContractor', NULL),
(16, 3, '1', 'Home', 'Rec''d 3/9'),
(17, 3, '1', 'Client', 'Sent 3/9'),
(18, 3, '1', 'Client', 'Returned 3/11 with comments'),
(19, 3, '1', 'Home', 'Fwd to sub'),
(20, 3, '2', 'SubContractor', NULL),
(21, 3, '2', 'Home', 'Rec''d 3/16'),
(22, 3, '2', 'Client', NULL),
(27, 2, '1', 'SubContractor', 'See client comment re fountain.'),
(28, 2, '2', 'Home', 'Fwd to ABC - John to review water wall'),
(29, 2, '2', 'Client', 'Approved'),
(30, 2, '2', 'Home', 'Update record');