--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:54:47 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO spms_erpmrp.`work codes`(ID, Description, Billable) VALUES
(1, 'Sick Time', 0),
(2, 'Vacation Time', 0),
(3, 'Administrative Tasks', 0),
(4, 'Project A', 1),
(5, 'Project B', 1);