--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.304.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/18/2020 8:34:42 AM
-- Server version: 8.0.20
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO mysql.bom(PartNum, PartName, Weight) VALUES
(1, 'Assembly 1', 0),
(2, 'Assembly 2', 0),
(3, 'Assembly 3', 0),
(4, 'Assembly 4', 0),
(5, 'Assembly 5', 0),
(6, 'Part 1', 10),
(7, 'Part 2', 5);